# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        files: backend/
        args:
          - --config
          - backend/pyproject.toml
          - backend
        exclude: .*/migrations/
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args:
          - backend
        exclude: .*/migrations/
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
        - id: flake8
          args:
            - --config
            - backend/.flake8
          exclude: .*/migrations/
