version: "3"
services:
  backend:
    image: gcr.io/academical/currency-exchanger-backend:latest
    build:
      context: backend
    ports:
    - 8000:8000
  rabbitmq:
    image: rabbitmq:3.8.9
  celery-worker:
    image: gcr.io/academical/currency-exchanger-backend:latest
    command: celery -A currency_exchanger worker -l INFO
    depends_on:
      - rabbitmq
    env_file:
      - backend/.env
volumes:
  postgres-data:
