version: "3"
services:
  backend:
    build:
      context: backend
    volumes:
    - ./backend:/app
    ports:
    - 8000:8000
    env_file:
      - backend/.env.development
  frontend:
    build:
      context: frontend
    volumes:
    - ./frontend/src:/app/src
    ports:
      - 8080:8080
  postgres:
    image: postgres:13.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: currency_exchanger
volumes:
  postgres-data:
