version: "3"
services:
  backend:
    build:
      context: backend
    volumes:
    - ./backend:/app
    ports:
    - 8000:8000
  frontend:
    build:
      context: frontend
    volumes:
    - ./frontend/src:/app/src
    ports:
      - 8080:8080
