# Generated by Django 3.1.2 on 2020-10-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='billingAddress_text',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='phone_text',
            new_name='phone',
        ),
    ]
