# Generated by Django 3.1.2 on 2020-11-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        ('currencies', '0002_auto_20201108_1701'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletstock',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='wallets.wallet'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='wallets.wallet'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='currencies.currency'),
        ),
    ]
