# Generated by Django 3.1.2 on 2020-11-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20201108_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletstock',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='walletstock',
            constraint=models.UniqueConstraint(fields=('wallet', 'stocks'), name='unique_wallet_stock'),
        ),
    ]
