# Generated by Django 3.1.2 on 2020-12-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201207_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
