# Generated by Django 3.1.2 on 2021-01-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20201219_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
