apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ include "currency-exchanger.name" . }}-backend
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
