apiVersion: v1
kind: Service
metadata:
  name: {{ include "currency-exchanger.name" . }}-frontend
  labels:
    {{- include "currency-exchanger.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "currency-exchanger.name" . }}-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "currency-exchanger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "currency-exchanger.name" . }}-frontend
