# Generated by Django 3.1.2 on 2020-12-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_add_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyexchange',
            name='amount_to',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
