# Generated by Django 3.1.2 on 2021-01-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_currencytransfer'),
        ('currencies', '0004_currencyexchange_amount_to'),
    ]

    operations = [
    ]
