# Generated by Django 3.1.2 on 2020-12-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_currencyexchange_amount_to'),
        ('currencies', '0004_currencytransfer'),
    ]

    operations = [
    ]
